compatibility_date = "2023-05-18"
name = "sonicjs"
workers_dev = true
main = "src/server.ts"
pages_build_output_dir = "./sonicjs/dist"

# Enter your account id
# This can be found at https://dash.cloudflare.com/ --> Workers & Pages
#  --> Overview, then in the right sidebar
account_id = "4ebc2a44d6307218371c62342678b2f6"

# Run the `wrangler kv:namespace create sonicjs` command and copy the id below
# Run the `wrangler kv:namespace create sonicjs --preview` command and copy the preview_id below
# Only update the preview_id and id, leave the binding name as "KVDATA"
kv_namespaces = [
  { binding = "KVDATA", preview_id="ad64e24b2b39486590aec4d70df9952f", id = "d2aad064476740118174bd6102f3db25" }
]

# Run the `wrangler d1 create sonicjs` command and copy the id below
[[d1_databases]]
binding = "D1DATA"
database_name = "sonicjs"
database_id = "cbc0f103-3368-4dbe-afb3-24564385fbe7"

# Using Cloudflare R2 (similar to AWS S3) is only necessary if you plan to use SonicJs to manage file assets
# Run the `wrangler r2 bucket create sonicjs` command and uncomment the section below
# [[r2_buckets]]
# inding = 'R2STORAGE' 
# bucket_name = 'sonicjs'

vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }
